### ISSUE TITLE
exception happened with a valid valid format in md file

### ISSUE THREAD

**Issue by metrue** [akfish/nice-place-for-coding-parser#1]
Hi @akfish 

the content of md file is:
<pre>
* 旧天堂书店 : 深圳市南山区华侨城创意园北区A5栋120 

```
  深圳一家比较出名的书店+咖啡，wifi速度不错，咖啡厅内有厕所，不用担心一个人离开座位太久东西失窃。消费大概在30元左右。

  from @jianzong 
```
</pre>

and here is parse testing script:
<pre>
var Parser = require('nice-place-for-coding-parser');
parser = new Parser();
places = parser.parse('./Shenzhen.md');
</pre>

the exception message is:
<pre>
/Users/huangmh/Codes/nice-place-for-coding/tools/data/node_modules/nice-place-for-coding-parser/lib/place-parser.js:31
      throw new Error("Source not empty but not place information was found");
            ^
Error: Source not empty but not place information was found
    at PlaceParser.module.exports.PlaceParser.parse (/Users/huangmh/Codes/nice-place-for-coding/tools/data/node_modules/nice-place-for-coding-parser/lib/place-parser.js:31:13)
    at Object.<anonymous> (/Users/huangmh/Codes/nice-place-for-coding/tools/data/upload_data.js:3:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
</pre>

would you please help take a look here?

**Comment by akfish** [comment]
`parser.parse` takes Markdown source code as the parameter, not the file name. You should read the file yourself.

**Comment by metrue** [comment]
@akfish 

got it.
